# Generated by Django 4.0.2 on 2022-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_company', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=120)),
                ('ram', models.CharField(choices=[('8', '8'), ('16', '16'), ('32', '32'), ('64', '64'), ('128', '128')], max_length=120)),
                ('secondary_memory', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=120)),
                ('secondary_storage', models.CharField(choices=[('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], max_length=120)),
                ('external_cooling', models.BooleanField()),
                ('case', models.CharField(blank=True, max_length=120, null=True)),
                ('psu', models.CharField(blank=True, max_length=120, null=True)),
                ('motherboard', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
